/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import classes.*;
import java.awt.Color;
import java.awt.Graphics;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Objects;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Fernanda
 */
public class frmMain extends javax.swing.JFrame {

    //
    javax.swing.JLabel prueba = new javax.swing.JLabel();
    DefaultTableModel tabla = new DefaultTableModel();
    DefaultTableModel tablaCPU = new DefaultTableModel();
    Reloj horaActual = new Reloj(); // hilo que muestra la hora del sistema
    Proceso[] atributosProceso;
    //variables insertar reloj
    //Fernanda

    String Proceso;
    private String TC;
    private String TL;
    public Integer contador = 0;
    //procesos automaticos

    /**
     * ************************ Variables Claudia ****************************
     */
    //ArrayList<Proceso> listaProcesos = new ArrayList();
    //int nuevaPosición=0;
    Integer proc = 0;
    int np = 0;
    int sumaT = 0;

    /**
     * Creates new form frmMain
     */
    public frmMain() {
        initComponents();
        this.setLocationRelativeTo(null);
        cargarProceso();
        cargardatos();
        horaActual.start();
        jTable1.setEnabled(false);
        jTable2.setEnabled(false);
        btnVaciar.setEnabled(false);
        jPNomenclatura.setVisible(false);
    }

    public void limpiarReloj() {
        //txtProceso.setText("");     
        txtTL.setText("");
        txtTC.setText("");
    }

    public void cargarProceso() {
        txtProceso.setText("P" + (contador));
    }

    public void cargardatos() {
        String[] titulo = new String[]{"PC", "TL", "TC"};
        tabla.setColumnIdentifiers(titulo);
        jTable1.setModel(tabla);

        String[] heders = new String[]{"ID", "Estado", "Hora Inicio", "Hora Final"};
        tablaCPU.setColumnIdentifiers(heders);
        jTable2.setModel(tablaCPU);
    }

    public void Insertar() {
        Proceso = txtProceso.getText();
        TL = txtTL.getText();
        TC = txtTC.getText();
        contador++;
        txtProceso.setText("P" + (contador));
    }

    /**
     * ************ Claudia ******************
     */
    public String[] listProcesos() {
        int fila = tabla.getRowCount();
        String[] lista = new String[tabla.getRowCount()];
        for (int c = 0; c < fila; c++) {

            lista[c] = tabla.getValueAt(c, 0).toString();
        }

        return lista;
    }

    public Integer[] listTL() {
        int fila = tabla.getRowCount();
        Integer[] lista = new Integer[tabla.getRowCount()];
        for (int c = 0; c < fila; c++) {

            lista[c] = Integer.parseInt(tabla.getValueAt(c, 1).toString());
        }
        return lista;
    }

    public Integer[] listarTC() {
        int fila = tabla.getRowCount();
        Integer[] lista = new Integer[tabla.getRowCount()];
        for (int c = 0; c < fila; c++) {
            lista[c] = Integer.parseInt(tabla.getValueAt(c, 2).toString());
        }
        return lista;
    }

    public void listTC() {
        int fila = tabla.getRowCount();
        for (int c = 0; c < fila; c++) {
            int valores = Integer.parseInt(tabla.getValueAt(c, 2).toString());
            sumaT = sumaT + valores;
        }
        //System.out.println(sumaT);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtProceso = new javax.swing.JTextField();
        txtTL = new javax.swing.JTextField();
        txtTC = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLHoraInicial = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLPlanificador = new javax.swing.JLabel();
        jLContadorPrograma = new javax.swing.JLabel();
        jLimite = new javax.swing.JLabel();
        jLBase = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jPMemoria = new javax.swing.JPanel();
        jPLabels = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        btnVaciar = new javax.swing.JButton();
        jPNomenclatura = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(1015, 709));
        setMinimumSize(new java.awt.Dimension(1015, 709));
        setResizable(false);

        txtProceso.setEditable(false);

        jButton2.setText("Insertar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("Iniciar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setText("Insertar datos");

        jLabel3.setText("Proceso");

        jLabel4.setText("TL");

        jLabel5.setText("TC");

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("Simulacion de Procesos");

        jLHoraInicial.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLHoraInicial.setText("Hora inicial del sistema: ");

        jLabel7.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        jLabel7.setText("jLabel7");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setText("0x800h");

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel8.setText("Memoria");

        jLabel9.setBackground(new java.awt.Color(153, 153, 255));
        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Sistema Operativo");
        jLabel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel9.setOpaque(true);
        jLabel9.setPreferredSize(new java.awt.Dimension(100, 18));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setText("0x000h");

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        jLabel15.setText("PLANIFICADOR");

        jLabel16.setText("Contador de programa");

        jLabel17.setText("Limite:");

        jLabel18.setText("Base:");

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jLPlanificador.setBackground(new java.awt.Color(153, 153, 153));
        jLPlanificador.setForeground(new java.awt.Color(0, 0, 0));
        jLPlanificador.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLPlanificador.setText("P0");
        jLPlanificador.setOpaque(true);

        jLContadorPrograma.setBackground(new java.awt.Color(153, 153, 153));
        jLContadorPrograma.setForeground(new java.awt.Color(0, 0, 0));
        jLContadorPrograma.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLContadorPrograma.setText("0");
        jLContadorPrograma.setOpaque(true);

        jLimite.setBackground(new java.awt.Color(153, 153, 153));
        jLimite.setForeground(new java.awt.Color(0, 0, 0));
        jLimite.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLimite.setText("0");
        jLimite.setOpaque(true);

        jLBase.setBackground(new java.awt.Color(153, 153, 153));
        jLBase.setForeground(new java.awt.Color(0, 0, 0));
        jLBase.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLBase.setText("0");
        jLBase.setOpaque(true);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(96, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(45, 45, 45))
                            .addComponent(jLPlanificador, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(63, 63, 63))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(jLContadorPrograma, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(88, 88, 88))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLimite, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLBase, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLPlanificador, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel16)
                .addGap(14, 14, 14)
                .addComponent(jLContadorPrograma, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jLimite, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jLBase, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );

        jLabel14.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel14.setText("CPU");

        jLabel21.setFont(new java.awt.Font("Dialog", 0, 16)); // NOI18N
        jLabel21.setText("Hora del sistema:");

        jPMemoria.setBackground(new java.awt.Color(255, 255, 255));
        jPMemoria.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPMemoria.setMaximumSize(new java.awt.Dimension(150, 405));
        jPMemoria.setMinimumSize(new java.awt.Dimension(150, 405));
        jPMemoria.setPreferredSize(new java.awt.Dimension(150, 405));

        javax.swing.GroupLayout jPMemoriaLayout = new javax.swing.GroupLayout(jPMemoria);
        jPMemoria.setLayout(jPMemoriaLayout);
        jPMemoriaLayout.setHorizontalGroup(
            jPMemoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 148, Short.MAX_VALUE)
        );
        jPMemoriaLayout.setVerticalGroup(
            jPMemoriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 405, Short.MAX_VALUE)
        );

        jPLabels.setMaximumSize(new java.awt.Dimension(50, 407));
        jPLabels.setMinimumSize(new java.awt.Dimension(50, 407));
        jPLabels.setPreferredSize(new java.awt.Dimension(50, 407));

        javax.swing.GroupLayout jPLabelsLayout = new javax.swing.GroupLayout(jPLabels);
        jPLabels.setLayout(jPLabelsLayout);
        jPLabelsLayout.setHorizontalGroup(
            jPLabelsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        jPLabelsLayout.setVerticalGroup(
            jPLabelsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 409, Short.MAX_VALUE)
        );

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel13.setText("0xFFFh");

        btnVaciar.setText("Reiniciar programa");
        btnVaciar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVaciarMouseClicked(evt);
            }
        });
        btnVaciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVaciarActionPerformed(evt);
            }
        });

        jLabel6.setBackground(new java.awt.Color(0, 255, 0));
        jLabel6.setMaximumSize(new java.awt.Dimension(25, 25));
        jLabel6.setMinimumSize(new java.awt.Dimension(25, 25));
        jLabel6.setOpaque(true);
        jLabel6.setPreferredSize(new java.awt.Dimension(25, 25));

        jLabel10.setBackground(new java.awt.Color(0, 51, 255));
        jLabel10.setMaximumSize(new java.awt.Dimension(25, 25));
        jLabel10.setMinimumSize(new java.awt.Dimension(25, 25));
        jLabel10.setOpaque(true);
        jLabel10.setPreferredSize(new java.awt.Dimension(25, 25));

        jLabel19.setBackground(new java.awt.Color(255, 0, 0));
        jLabel19.setMaximumSize(new java.awt.Dimension(25, 25));
        jLabel19.setMinimumSize(new java.awt.Dimension(25, 25));
        jLabel19.setOpaque(true);
        jLabel19.setPreferredSize(new java.awt.Dimension(25, 25));

        jLabel20.setText("ESTADO: EJECUTANDOSE");

        jLabel22.setText("ESTADO: LISTO");

        jLabel23.setText("RECORRIDO CONTADOR DE PROGRAMA");

        javax.swing.GroupLayout jPNomenclaturaLayout = new javax.swing.GroupLayout(jPNomenclatura);
        jPNomenclatura.setLayout(jPNomenclaturaLayout);
        jPNomenclaturaLayout.setHorizontalGroup(
            jPNomenclaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPNomenclaturaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPNomenclaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPNomenclaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPNomenclaturaLayout.createSequentialGroup()
                        .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPNomenclaturaLayout.setVerticalGroup(
            jPNomenclaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPNomenclaturaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPNomenclaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPNomenclaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPNomenclaturaLayout.createSequentialGroup()
                        .addGroup(jPNomenclaturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel20))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel23, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLHoraInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(284, 284, 284)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(288, 288, 288)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(txtProceso, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addComponent(txtTL, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addComponent(txtTC, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(41, 41, 41)
                                .addComponent(btnVaciar, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPNomenclatura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(66, 66, 66)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(2, 2, 2)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jPMemoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(64, 64, 64)
                                .addComponent(jPLabels, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(77, 77, 77)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(10, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLHoraInicial))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8)
                        .addComponent(jLabel2))
                    .addComponent(jLabel14))
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(jLabel3))
                            .addComponent(txtProceso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(jLabel4))
                            .addComponent(txtTL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(jLabel5))
                            .addComponent(txtTC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(61, 61, 61)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1)
                            .addComponent(btnVaciar))
                        .addGap(18, 18, 18)
                        .addComponent(jPNomenclatura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPLabels, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPMemoria, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, 0)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(jLabel12)
                                .addGap(70, 70, 70)
                                .addComponent(jLabel11))
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(jLabel21)
                        .addGap(9, 9, 9)
                        .addComponent(jLabel7)))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        //jTable1.addRow()
        Insertar();
        tabla.addRow(new Object[]{Proceso, TL, TC});
        limpiarReloj();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        //listTL();
        RR roundrobin = new RR();
        listTC();
        //if (sumaT <= 30) {
        jLHoraInicial.setText("Hora inicial del sistema: " + jLabel7.getText());
        jPNomenclatura.setVisible(true);
        roundrobin.start();
        /*} else {
            roundrobin.Error();
        }*/

        txtTC.setEnabled(false);
        txtTL.setEnabled(false);
        jButton2.setEnabled(false);
        jButton1.setEnabled(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnVaciarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVaciarMouseClicked
        // TODO add your handling code here:
        sumaT=0;
        txtTC.setEnabled(true);
        txtTL.setEnabled(true);
        jButton2.setEnabled(true);
        jButton1.setEnabled(true);
        for (int i = 0; i < tabla.getRowCount(); i++) {
            tabla.removeRow(i);
            tablaCPU.removeRow(i);
            i -= 1;
        }
        contador = 0;
        txtProceso.setText("P0");
        jLPlanificador.setText("P0");
        jLContadorPrograma.setText("0");
        jLimite.setText("0");
        jLBase.setText("0");

        btnVaciar.setEnabled(false);
    }//GEN-LAST:event_btnVaciarMouseClicked

    private void btnVaciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVaciarActionPerformed
        // TODO add your handling code here:
        sumaT=0;
        txtTC.setEnabled(true);
        txtTL.setEnabled(true);
        jButton2.setEnabled(true);
        jButton1.setEnabled(true);
        for (int i = 0; i < tabla.getRowCount(); i++) {
            tabla.removeRow(i);
            tablaCPU.removeRow(i);
            i -= 1;
        }
        contador = 0;
        txtProceso.setText("P0");
        jLPlanificador.setText("P0");
        jLContadorPrograma.setText("0");
        jLimite.setText("0");
        jLBase.setText("0");

        btnVaciar.setEnabled(false);
    }//GEN-LAST:event_btnVaciarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMain().setVisible(true);
            }
        });
    }
    // clase para la hora del sistema. ¡No modificar!

    public class Reloj extends Thread {

        Calendar calendario;

        @Override
        public void run() {
            while (true) {
                String horaSistema = "";
                calendario = Calendar.getInstance();
                if (calendario.get(Calendar.HOUR_OF_DAY) < 10) {
                    horaSistema += String.valueOf("0" + calendario.get(Calendar.HOUR_OF_DAY)) + ":";
                } else {
                    horaSistema += String.valueOf(calendario.get(Calendar.HOUR_OF_DAY)) + ":";
                }
                if (calendario.get(Calendar.MINUTE) < 10) {
                    horaSistema += String.valueOf("0" + calendario.get(Calendar.MINUTE)) + ":";
                } else {
                    horaSistema += String.valueOf(calendario.get(Calendar.MINUTE)) + ":";
                }
                if (calendario.get(Calendar.SECOND) < 10) {
                    horaSistema += String.valueOf("0" + calendario.get(Calendar.SECOND)) + "hrs";
                } else {
                    horaSistema += String.valueOf(calendario.get(Calendar.SECOND)) + " hrs";
                }
                //horaSistema += String.valueOf(calendario.get(Calendar.MILLISECOND)) + " hrs";
                jLabel7.setText(horaSistema);
                try {
                    Thread.sleep(1);
                } catch (InterruptedException ex) {
                    Logger.getLogger(frmMain.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }

    public void insertarHistorial(String id, String Estado, String HL, String HF) {
        tablaCPU.addRow(new Object[]{id, Estado, HL, HF});
    }
    
    public class RR extends Thread {
        public void Error(String proceso) {
        String ms1 = "<html><p style = \"color:white; font:15px; \">  MEMORIA INCUFICIENTE </br>" 
                + proceso + " NO CABE </p></html>";
        JOptionPane.showMessageDialog(null, ms1, " ", JOptionPane.ERROR_MESSAGE);
        }
        @Override
        public void run() {
            //Poner todas las entradas en 0
            String[] listaPlanifador = listProcesos();
            Integer[] listaTiempoEntrada = listTL();
            Integer[] listaTiempoProceso = listarTC();
            Boolean[] entradadeProceso = new Boolean[listaPlanifador.length];
            Boolean[] atendiendo = new Boolean[listaPlanifador.length];
            Boolean[] terminado = new Boolean[listaPlanifador.length];
            Boolean[] verificado = new Boolean[listaPlanifador.length];
            Boolean[] hora = new Boolean[listaPlanifador.length];
            Integer numeroProcesos = listaPlanifador.length;
            Integer quantum = 4;
            Integer aux;
            Integer aux3 = 0, tiempos = 0, aceptados=0;
            String aux2;
            boolean enCola = false; // variable para saber si existen procesos en cola o si ya todos fueron verificados.
            int contador = 0;
            atributosProceso = new Proceso[listaPlanifador.length];
            int basey = jPMemoria.getHeight() - 1;
            int base = 2049;
            //inicializar variable atributoProceso
            //Ordenar el orden de llegada 
            for (int i = 0; i < numeroProcesos; i++) {
                for (int j = 0; j < numeroProcesos - 1; j++) {
                    if (listaTiempoEntrada[j] > listaTiempoEntrada[j + 1]) {
                        //Ordenar Segundos de llegada
                        aux = listaTiempoEntrada[j + 1];
                        listaTiempoEntrada[j + 1] = listaTiempoEntrada[j];
                        listaTiempoEntrada[j] = aux;
                        //Ordenar Segundos de Proceso
                        aux = listaTiempoProceso[j + 1];
                        listaTiempoProceso[j + 1] = listaTiempoProceso[j];
                        listaTiempoProceso[j] = aux;
                        //Ordenar Proceso 
                        aux2 = listaPlanifador[j + 1];
                        listaPlanifador[j + 1] = listaPlanifador[j];
                        listaPlanifador[j] = aux2;
                    }
                }

            }
            for (int i = 0; i < numeroProcesos; i++) {
                entradadeProceso[i] = false;
                atendiendo[i] = false;
                terminado[i] = false;
                verificado[i] = false;
                hora[i] = false;
                atributosProceso[i] = new Proceso(listaTiempoProceso[i], listaPlanifador[i]);
            }
            aux = 0;
            while (true) {
//Control de entrada
                for (int i = 0; i < numeroProcesos; i++) {
                    if (listaTiempoEntrada[i] == 0 && entradadeProceso[i] != true) {
                       if (tiempos + listaTiempoProceso[i] <= 30 && !verificado[i]) {
                            tiempos = tiempos + listaTiempoProceso[i];
                            entradadeProceso[i] = true;
                            verificado[i] = true;
                            //insertarHistorial(listaPlanifador[i], "Listo", jLabel7.getText(), "");
                            insertarHistorial(listaPlanifador[i], "Listo", "", "");
                            Grafica.hacerGrafica(jPMemoria.getGraphics(), 1, basey - atributosProceso[i].getTamanioEnPix(), 148, atributosProceso[i].getTamanioEnPix(), listaPlanifador[i], Color.BLUE);
                            atributosProceso[i].setPosicion(basey - atributosProceso[i].getTamanioEnPix());
                            basey = basey - atributosProceso[i].getTamanioEnPix();
                            atributosProceso[i].setPlanificador(base);
                            atributosProceso[i].setBaseHexa(Integer.toHexString(base));
                            atributosProceso[i].setLimiteHexa(Integer.toHexString(base + atributosProceso[i].getTamanio()));
                            atributosProceso[i].setPosicionTabla(aceptados);
                            base = 1 + base + atributosProceso[i].getTamanio();
                            aceptados++;
                        }
                        else if(tiempos + listaTiempoProceso[i] > 30 && !verificado[i])
                        {
                            Error(listaPlanifador[i]);
                            verificado[i] = true;
                        }
                       enCola=false;
                    } 
                    else {
                        if (listaTiempoEntrada[i] > 0) {
                            listaTiempoEntrada[i] = listaTiempoEntrada[i] - 1;
                            enCola = true;
                        }
                    }
                }

//Control de para antender 
                //Asigno a quien atender
                for (int i = aux; i < numeroProcesos; i++) {
                    if (entradadeProceso[i] == true && atendiendo[i] == false && quantum == 4 && listaTiempoProceso[i] > 0) {
                        aux3 = i;
                        atendiendo[i] = true;
                        jLPlanificador.setText(listaPlanifador[i]);
                        Grafica.hacerGrafica(jPMemoria.getGraphics(), 1, atributosProceso[i].getPosicion(), 148, atributosProceso[i].getTamanioEnPix(), listaPlanifador[i], Color.GREEN);
                        Grafica.labelGrafica(jPLabels.getGraphics(), 1, atributosProceso[i].getPosicion(), atributosProceso[i].getTamanioEnPix(), atributosProceso[i].getBaseHexa(), atributosProceso[i].getLimiteHexa());
                        jLimite.setText(atributosProceso[i].getLimiteHexa());
                        jLBase.setText(atributosProceso[i].getBaseHexa());
                        aux = i + 1;
                        break;
                    }
                }
                //Restauramos el quantum

                if (quantum == 0 || listaTiempoProceso[aux3] == 0) {
                    quantum = 4;
                    if (aux == numeroProcesos && entradadeProceso[tabla.getRowCount()-1]==true) {    
                        aux = 0;
                    }
                    else if(aux == aceptados && entradadeProceso[tabla.getRowCount()-1]==false){
                        aux = 0;
                    }
                    if (atendiendo[aux3]) {
                        tablaCPU.setValueAt("Listo", atributosProceso[aux3].getPosicionTabla(), 1);
                        atendiendo[aux3] = false;
                        Grafica.hacerGrafica(jPMemoria.getGraphics(), 1, atributosProceso[aux3].getPosicion(), 148, atributosProceso[aux3].getTamanioEnPix(), listaPlanifador[aux3], Color.BLUE);
                        Grafica.recorridodoGrafica(jPMemoria.getGraphics(), 1, atributosProceso[aux3].getPosicion(), 148, atributosProceso[aux3].getTamanioEnPix(), listaPlanifador[aux3], atributosProceso[aux3].getTiempo() - listaTiempoProceso[aux3], Color.BLACK);
                    }
                    if (listaTiempoProceso[aux3] == 0 && terminado[aux3] == false) {
                        //System.out.println("PROCESO " + listaPlanifador[aux3] + " TERMINADO HORA: " + jLabel7.getText());
                        tablaCPU.setValueAt(jLabel7.getText(), atributosProceso[aux3].getPosicionTabla(), 3);
                        tablaCPU.setValueAt("Terminado", atributosProceso[aux3].getPosicionTabla(), 1);
                        terminado[aux3] = true;
                        //Grafica.hacerGrafica(jPMemoria.getGraphics(), 1, atributosProceso[aux3].getPosicion(), 147, atributosProceso[aux3].getTamanioEnPix(), listaPlanifador[aux3], Color.GRAY);
                        Grafica.eliminarGrafica(jPMemoria.getGraphics(), 1, atributosProceso[aux3].getPosicion(), 148, atributosProceso[aux3].getTamanioEnPix());
                        contador++;
                        
                        //Condicion para terminar el hilo (Si todos fueron verificados y no existen en cola)
                        if ((contador == aceptados) && !enCola) {
                            btnVaciar.setEnabled(true);
                            jPNomenclatura.setVisible(false);
                            Grafica.limpiarLabels(jPLabels.getGraphics());
                            break;
                        }
                    }
                } else if (entradadeProceso[aux3] == true && atendiendo[aux3] == true) {
                    //Atiende
                    //Condicion que coloca la hora en el sistema la primera vez que es ejecutado
                    if(!hora[aux3]){
                        tablaCPU.setValueAt(jLabel7.getText(), atributosProceso[aux3].getPosicionTabla(), 2);
                        hora[aux3] = true;
                    }
                    
                    quantum = quantum - 1;
                    listaTiempoProceso[aux3] = listaTiempoProceso[aux3] - 1;
                    tablaCPU.setValueAt("Ejecutando", atributosProceso[aux3].getPosicionTabla(), 1);
                    jLContadorPrograma.setText("0x" + Integer.toHexString(atributosProceso[aux3].getPlanificador() + (atributosProceso[aux3].getTiempo() - listaTiempoProceso[aux3]) * 68).toUpperCase() + "h");
                    Grafica.recorridodoGrafica(jPMemoria.getGraphics(), 1, atributosProceso[aux3].getPosicion(), 148, atributosProceso[aux3].getTamanioEnPix(), listaPlanifador[aux3], atributosProceso[aux3].getTiempo() - listaTiempoProceso[aux3], Color.YELLOW);
                }

                try {
                    Thread.sleep(845);
                } catch (InterruptedException ex) {
                    Logger.getLogger(frmMain.class.getName()).log(Level.SEVERE, null, ex);
                }
 
            }
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVaciar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLBase;
    private javax.swing.JLabel jLContadorPrograma;
    private javax.swing.JLabel jLHoraInicial;
    private javax.swing.JLabel jLPlanificador;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLimite;
    private javax.swing.JPanel jPLabels;
    public javax.swing.JPanel jPMemoria;
    private javax.swing.JPanel jPNomenclatura;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField txtProceso;
    private javax.swing.JTextField txtTC;
    private javax.swing.JTextField txtTL;
    // End of variables declaration//GEN-END:variables
}
